import { supabase, supabaseConfigured } from './supabase';
export async function signInAdmin(email: string,password: string){if(!supabaseConfigured||!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;return data;}
export async function getAdminDashboard(){if(!supabase)throw new Error('Supabase no está configurado.');const [{data:profile},{data:bookings,error}]=await Promise.all([supabase.from('admin_profiles').select('display_name,active').single(),supabase.from('bookings').select('id,public_reference,preferred_date,participant_count,status,created_at,customers(full_name,email),routes(title)').order('created_at',{ascending:false}).limit(25)]);if(error)throw error;if(!profile?.active)throw new Error('La cuenta no tiene acceso administrativo activo.');return {profile,bookings:bookings??[]};}
export const bookingStatuses=['received','reviewing','confirmed','cancelled','completed'] as const; export type BookingStatus=typeof bookingStatuses[number]; export interface BookingFilters{page?:number;pageSize?:number;query?:string;routeId?:string;date?:string;status?:BookingStatus|'';}
export async function getBookingRoutes(){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.from('routes').select('id,title').order('title');if(error)throw error;return data??[];}
export async function getBookings(f:BookingFilters={}){if(!supabase)throw new Error('Supabase no está configurado.');const page=Math.max(f.page??1,1),pageSize=f.pageSize??20;let q=supabase.from('bookings').select('id,public_reference,preferred_date,preferred_time,language,participant_count,modality,special_requests,internal_notes,status,created_at,updated_at,customers(full_name,email,phone),routes(id,title)',{count:'exact'}).order('created_at',{ascending:false});if(f.routeId)q=q.eq('route_id',f.routeId);if(f.date)q=q.eq('preferred_date',f.date);if(f.status)q=q.eq('status',f.status);if(f.query?.trim()){const s=f.query.trim().replace(/[,().]/g,' ');q=q.or(`public_reference.ilike.%${s}%,customers.full_name.ilike.%${s}%,customers.email.ilike.%${s}%`);}const {data,error,count}=await q.range((page-1)*pageSize,page*pageSize-1);if(error)throw error;return {bookings:data??[],total:count??0,page,pageSize};}
export async function getBookingHistory(id:string){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.from('audit_log').select('id,action,details,created_at').eq('entity_type','booking').eq('entity_id',id).order('created_at',{ascending:false});if(error)throw error;return data??[];}
export async function manageBooking(id:string,status:BookingStatus,notes:string){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.rpc('manage_booking',{p_booking_id:id,p_status:status,p_internal_notes:notes});if(error)throw error;return data;}
export async function getAdminRoutes(){if(!supabase)throw new Error('Supabase no está configurado.');const [{data:routes,error:routesError},{data:drafts,error:draftsError}]=await Promise.all([supabase.from('routes').select('id,slug,title,eyebrow,promise,full_description,display_price_individual,status,sort_order').order('sort_order'),supabase.from('route_drafts').select('route_id,content,updated_at')]);if(routesError)throw routesError;if(draftsError)throw draftsError;const draftsByRoute=new Map((drafts??[]).map(d=>[d.route_id,d]));return (routes??[]).map(route=>({...route,draft:draftsByRoute.get(route.id)??null}));}
export async function saveRouteDraft(id:string,payload:{title:string;eyebrow:string;promise:string;description:string;price:string}){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.rpc('save_route_draft',{p_route_id:id,p_payload:{title:payload.title,eyebrow:payload.eyebrow,promise:payload.promise,full_description:payload.description,display_price_individual:payload.price}});if(error)throw error;return data;}
export async function publishRouteDraft(id:string){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.rpc('publish_route_draft',{p_route_id:id});if(error)throw error;const {error:deployError}=await supabase.functions.invoke('trigger-site-deploy');if(deployError)throw new Error('La ruta se publicó en la base de datos, pero no fue posible iniciar la actualización de la web. Inténtalo de nuevo.');return data;}
export async function getRouteHistory(id:string){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.from('audit_log').select('id,action,details,created_at').eq('entity_type','route').eq('entity_id',id).eq('action','route_updated').order('created_at',{ascending:false});if(error)throw error;return data??[];}
export async function revertRouteRevision(auditId:number){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.rpc('revert_route_revision',{p_audit_id:auditId});if(error)throw error;const {error:deployError}=await supabase.functions.invoke('trigger-site-deploy');if(deployError)throw new Error('El cambio se revirtió en la base de datos, pero no fue posible iniciar la actualización de la web. Inténtalo de nuevo.');return data;}
export async function duplicateAdminRoute(id:string,title:string){if(!supabase)throw new Error('Supabase no está configurado.');const {data,error}=await supabase.rpc('duplicate_route',{p_route_id:id,p_new_title:title});if(error)throw error;return data;}