// @ts-nocheck
import { supabase } from '../lib/supabase'; import { signInAdmin,getAdminDashboard } from '../lib/admin';
const app=document.querySelector('[data-admin-app]');
if(app){
 const login=app.querySelector('[data-login-view]'),dashboard=app.querySelector('[data-dashboard]'),sidebar=app.querySelector('[data-admin-sidebar]'),errorNode=app.querySelector('[data-admin-error]');
 const setError=(m='')=>errorNode.textContent=m;
 async function load(){const data=await getAdminDashboard();login.hidden=true;dashboard.hidden=false;sidebar.hidden=false;app.querySelector('[data-admin-name]').textContent=data.profile.display_name||'Administrador';const counts={received:0,reviewing:0,confirmed:0,total:data.bookings.length};data.bookings.forEach(b=>{if(counts[b.status]!==undefined)counts[b.status]++});Object.entries(counts).forEach(([k,v])=>app.querySelector(`[data-metric="${k}"]`).textContent=String(v));const body=app.querySelector('[data-bookings-body]');body.innerHTML='';data.bookings.forEach(b=>{const customer=Array.isArray(b.customers)?b.customers[0]:b.customers;const route=Array.isArray(b.routes)?b.routes[0]:b.routes;const row=document.createElement('tr');row.innerHTML=`<td><strong>${b.public_reference}</strong></td><td>${customer?.full_name||'—'}<small>${customer?.email||''}</small></td><td>${route?.title||'—'}</td><td>${b.preferred_date}</td><td>${b.participant_count}</td><td><span class="booking-state ${b.status}">${b.status}</span></td>`;body.appendChild(row)});app.querySelector('[data-admin-empty]').hidden=data.bookings.length>0;}
 app.querySelector('[data-login-form]')?.addEventListener('submit',async ev=>{ev.preventDefault();const f=ev.currentTarget,b=f.querySelector('button');b.disabled=true;try{await signInAdmin(f.email.value,f.password.value);await load()}catch(e){setError(e.message||'No fue posible entrar.')}finally{b.disabled=false;b.textContent='Entrar'}});
 app.querySelector('[data-refresh]')?.addEventListener('click',()=>load().catch(e=>setError(e.message)));app.querySelector('[data-signout]')?.addEventListener('click',async()=>{await supabase?.auth.signOut();location.reload()});app.querySelectorAll('[data-admin-view]').forEach(button=>button.addEventListener('click',()=>{app.querySelectorAll('[data-admin-view]').forEach(b=>b.classList.remove('active'));button.classList.add('active');app.querySelectorAll('[data-view]').forEach(view=>view.hidden=view.dataset.view!==button.dataset.adminView)}));if(supabase)supabase.auth.getSession().then(({data})=>{if(data.session)load().catch(()=>supabase.auth.signOut())});
}
